// AI output validation layer
// Purpose: Catch obvious AI errors before displaying results to clinicians

import type { PatientProfile, MockTrial } from '@/types';

interface ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Validates patient profile extracted by AI
 * Catches unrealistic values and medical contradictions
 */
export const validatePatientProfile = (profile: PatientProfile): ValidationResult => {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Age validation (18-120 years)
  if (profile.age < 18) {
    errors.push(`Age ${profile.age} is below minimum (18 years)`);
  } else if (profile.age > 120) {
    errors.push(`Age ${profile.age} is unrealistic (max 120 years)`);
  } else if (profile.age === 0) {
    warnings.push('Age not extracted, defaulting to unknown');
  }

  // Cancer stage validation (I, II, III, IV, or null)
  if (profile.stage) {
    const normalizedStage = profile.stage.toUpperCase().replace(/STAGE\s*/i, '').trim();
    const validStages = ['I', 'IA', 'IB', 'II', 'IIA', 'IIB', 'III', 'IIIA', 'IIIB', 'IIIC', 'IV', 'IVA', 'IVB'];
    
    if (!validStages.some(valid => normalizedStage.startsWith(valid))) {
      errors.push(`Invalid cancer stage: "${profile.stage}". Must be I, II, III, or IV`);
    }

    // Check for impossible combinations
    if (normalizedStage === '0' && profile.conditions.some(c => c.toLowerCase().includes('metastatic'))) {
      errors.push('Impossible combination: Stage 0 cannot be metastatic');
    }
  }

  // ECOG performance status validation (0-5)
  if (profile.performanceStatus) {
    const ecogMatch = profile.performanceStatus.match(/ECOG\s*(\d)/i);
    if (ecogMatch) {
      const ecogScore = parseInt(ecogMatch[1]);
      if (ecogScore < 0 || ecogScore > 5) {
        errors.push(`Invalid ECOG score: ${ecogScore}. Must be 0-5`);
      }
    }
  }

  // Biomarker contradiction checks
  const biomarkerKeys = Object.keys(profile.biomarkers).map(k => k.toLowerCase());
  const biomarkerValues = Object.values(profile.biomarkers).map(v => v.toLowerCase());
  
  // TNBC (Triple Negative) cannot be HER2+, ER+, or PR+
  const isTNBC = profile.conditions.some(c => c.toLowerCase().includes('triple negative') || c.toLowerCase().includes('tnbc'));
  const hasHER2Positive = biomarkerKeys.includes('her2') && biomarkerValues.some(v => v.includes('positive') || v.includes('+'));
  const hasERPositive = biomarkerKeys.includes('er') && biomarkerValues.some(v => v.includes('positive') || v.includes('+'));
  const hasPRPositive = biomarkerKeys.includes('pr') && biomarkerValues.some(v => v.includes('positive') || v.includes('+'));

  if (isTNBC && (hasHER2Positive || hasERPositive || hasPRPositive)) {
    errors.push('Biomarker contradiction: Triple Negative Breast Cancer cannot be HER2+, ER+, or PR+');
  }

  // Check for missing critical data
  if (profile.conditions.length === 0) {
    warnings.push('No conditions/diagnoses extracted from patient notes');
  }

  if (!profile.stage && profile.conditions.some(c => c.toLowerCase().includes('cancer'))) {
    warnings.push('Cancer stage not specified - may limit trial matching accuracy');
  }

  if (Object.keys(profile.biomarkers).length === 0 && profile.conditions.some(c => c.toLowerCase().includes('breast cancer'))) {
    warnings.push('No biomarkers (HER2, ER, PR) extracted - critical for breast cancer trial matching');
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
};

/**
 * Validates mock trials generated by AI
 * Ensures exactly 3 trials with required fields and realistic data
 */
export const validateMockTrials = (trials: MockTrial[]): ValidationResult => {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Must have exactly 3 trials
  if (trials.length !== 3) {
    errors.push(`Expected exactly 3 trials, got ${trials.length}`);
  }

  // Validate each trial
  trials.forEach((trial, index) => {
    const trialNum = index + 1;

    // NCT ID format validation
    if (!trial.nctId || !trial.nctId.match(/^NCT\d{8}$/)) {
      errors.push(`Trial ${trialNum}: Invalid NCT ID format "${trial.nctId}". Must be NCT + 8 digits`);
    }

    // Required fields
    if (!trial.title || trial.title.length < 10) {
      errors.push(`Trial ${trialNum}: Title missing or too short`);
    }

    if (!trial.phase || !['Phase 1', 'Phase 2', 'Phase 3'].includes(trial.phase)) {
      errors.push(`Trial ${trialNum}: Invalid phase "${trial.phase}". Must be Phase 1, 2, or 3`);
    }

    if (!trial.briefSummary || trial.briefSummary.length < 20) {
      errors.push(`Trial ${trialNum}: Brief summary missing or too short`);
    }

    // Criteria validation
    if (!trial.inclusionCriteria || trial.inclusionCriteria.length < 3) {
      errors.push(`Trial ${trialNum}: Must have at least 3 inclusion criteria`);
    }

    if (!trial.exclusionCriteria || trial.exclusionCriteria.length < 2) {
      errors.push(`Trial ${trialNum}: Must have at least 2 exclusion criteria`);
    }

    // Match type validation
    if (!['perfect', 'excluded', 'uncertain'].includes(trial.matchType)) {
      errors.push(`Trial ${trialNum}: Invalid matchType "${trial.matchType}". Must be perfect, excluded, or uncertain`);
    }

    // Match score validation
    if (trial.matchScore < 0 || trial.matchScore > 100) {
      errors.push(`Trial ${trialNum}: Match score ${trial.matchScore} out of range (0-100)`);
    }

    // Score should align with matchType
    if (trial.matchType === 'perfect' && trial.matchScore < 85) {
      warnings.push(`Trial ${trialNum}: "perfect" match has low score (${trial.matchScore}). Expected 85+`);
    }

    if (trial.matchType === 'excluded' && trial.matchScore > 30) {
      warnings.push(`Trial ${trialNum}: "excluded" match has high score (${trial.matchScore}). Expected <30`);
    }

    if (trial.matchType === 'uncertain' && (trial.matchScore < 40 || trial.matchScore > 75)) {
      warnings.push(`Trial ${trialNum}: "uncertain" match score (${trial.matchScore}) outside typical range (40-75)`);
    }
  });

  // Check for matchType distribution (should have 1 of each)
  const matchTypes = trials.map(t => t.matchType);
  const hasPerfect = matchTypes.includes('perfect');
  const hasExcluded = matchTypes.includes('excluded');
  const hasUncertain = matchTypes.includes('uncertain');

  if (!hasPerfect || !hasExcluded || !hasUncertain) {
    warnings.push('Expected 1 perfect, 1 excluded, and 1 uncertain trial for demo variety');
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
};

/**
 * Sanitizes patient profile by fixing common AI extraction errors
 * Returns corrected profile with fixes applied
 */
export const sanitizePatientProfile = (profile: PatientProfile): PatientProfile => {
  const sanitized = { ...profile };

  // Fix age bounds
  if (sanitized.age < 0) sanitized.age = 0;
  if (sanitized.age > 120) sanitized.age = 120;

  // Normalize stage format
  if (sanitized.stage) {
    sanitized.stage = sanitized.stage
      .replace(/stage\s*/i, 'Stage ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  // Normalize ECOG format
  if (sanitized.performanceStatus && !sanitized.performanceStatus.toUpperCase().startsWith('ECOG')) {
    const ecogMatch = sanitized.performanceStatus.match(/(\d)/);
    if (ecogMatch) {
      sanitized.performanceStatus = `ECOG ${ecogMatch[1]}`;
    }
  }

  // Normalize biomarker keys to standard format
  const normalizedBiomarkers: Record<string, string> = {};
  Object.entries(sanitized.biomarkers).forEach(([key, value]) => {
    const normalizedKey = key.toUpperCase().replace(/[^A-Z0-9]/g, '');
    normalizedBiomarkers[normalizedKey] = value;
  });
  sanitized.biomarkers = normalizedBiomarkers;

  return sanitized;
};

/**
 * Sanitizes mock trials by fixing common AI generation errors
 * Returns corrected trials array
 */
export const sanitizeMockTrials = (trials: MockTrial[]): MockTrial[] => {
  return trials.slice(0, 3).map(trial => ({
    ...trial,
    // Ensure NCT ID format
    nctId: trial.nctId.match(/NCT\d{8}/) ? trial.nctId : `NCT${Math.floor(10000000 + Math.random() * 90000000)}`,
    // Normalize phase format
    phase: trial.phase.includes('1') ? 'Phase 1' : trial.phase.includes('2') ? 'Phase 2' : 'Phase 3',
    // Clamp match score
    matchScore: Math.max(0, Math.min(100, trial.matchScore)),
    // Ensure matchType is valid
    matchType: ['perfect', 'excluded', 'uncertain'].includes(trial.matchType) ? trial.matchType : 'uncertain',
  }));
};
